import { z, defineCollection } from 'astro:content';

const services = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    description: z.string(),
    category: z.enum(['accueil', 'etrangers', 'social', 'documents', 'famille', 'personne']),
    price: z.string().optional(),
    icon: z.string().optional(),
    image: z.string().optional(),
    badge: z.string().optional(),
    whatsappText: z.string().optional(),
    order: z.number().default(0),
    featured: z.boolean().default(false),
  }),
});

const blog = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    description: z.string(),
    pubDate: z.date(),
    updatedDate: z.date().optional(),
    category: z.enum(['accueil', 'etrangers', 'social', 'documents', 'famille', 'personne', 'general']),
    tags: z.array(z.string()).default([]),
    author: z.string().default('MPS Team'),
    image: z.string().optional(),
    featured: z.boolean().default(false),
    readingTime: z.number().optional(),
  }),
});

const tarifs = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    price: z.string(),
    description: z.string(),
    includes: z.array(z.string()),
    badge: z.string().optional(),
    stripePriceId: z.string().optional(),
    popular: z.boolean().default(false),
    order: z.number().default(0),
  }),
});

const annonces = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    description: z.string(),
    dateStart: z.date(),
    dateEnd: z.date().optional(),
    type: z.enum(['offre', 'recrutement', 'partenariat', 'actualite']),
    badgeColor: z.string().default('blue'),
    active: z.boolean().default(true),
  }),
});

const faq = defineCollection({
  type: 'content',
  schema: z.object({
    question: z.string(),
    answer: z.string(),
    category: z.string(),
    order: z.number().default(0),
  }),
});

const news = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    sourceUrl: z.string(),
    pubDate: z.date(),
    autoGenerated: z.boolean().default(false),
    validated: z.boolean().default(false),
    category: z.string().default('general'),
  }),
});

export const collections = { services, blog, tarifs, annonces, faq, news };
